- name: Set git name 
  git_config:
    name: user.name
    scope: global
    value: "{{ git_name }}"
  become: False

- name: Set git email 
  git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"
  become: False

- name: Set git default push
  git_config:
    name: push.default
    scope: global
    value: "matching"
  become: False
  
- name: Set git default editor
  git_config:
    name: core.editor
    scope: global
    value: vim
  become: False

- name: Set git color ui
  git_config:
    name: color.ui
    scope: global
    value: auto
  become: False

- name: Set vim as default editor
  lineinfile:
    dest: ~/.bashrc
    regexp: '^export EDITOR='
    line: 'export EDITOR=vim'

- name: Add cc alias
  lineinfile:
    dest: ~/.bashrc
    regexp: 'alias cc='
    line: "alias cc='cd \"$(pwd)\"'"

- name: Create or attach to tmux session
  lineinfile:
    dest: ~/.bashrc
    regexp: '^(.*)tmux -2 new-session -A -s initial(.*)'
    line: '{{ tmux }}'

- name: Set autocd in bashrc
  lineinfile:
    dest: ~/.bashrc
    regexp: 'shopt -s autocd'
    line: 'shopt -s autocd'

- name: Prettier log
  git_config:
    name: alias.lg
    scope: global
    value: 'log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr, %cn)%Creset" --abbrev-commit --date=relative'

- name: XFCE4 Terminal config
  copy: 
    src: "{{ role_path }}/files/terminalrc"
    dest: "~/.config/xfce4/terminal"
    backup: yes
  ignore_errors: yes
  tags: test

- name: XFCE4 Keybindings
  copy: 
    src: "{{ role_path }}/files/xfce4-keyboard-shortcuts.xml"
    dest: "~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
    backup: yes
  ignore_errors: yes
  tags: test

