---

- name: Set git name
  git_config:
    name: user.name
    scope: global
    value: "{{ git_name }}"
  become: false

- name: Set git email
  git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"
  become: false

- name: Set git default push
  git_config:
    name: push.default
    scope: global
    value: "matching"
  become: false

- name: Set git default editor
  git_config:
    name: core.editor
    scope: global
    value: vim
  become: false

- name: Set git color ui
  git_config:
    name: color.ui
    scope: global
    value: auto
  become: false

- name: Set vim as default editor
  lineinfile:
    dest: ~/.bashrc
    regexp: '^export EDITOR='
    line: 'export EDITOR=vim'

- name: Add cc alias
  lineinfile:
    dest: ~/.bashrc
    regexp: 'alias cc='
    line: "alias cc='cd \"$(pwd)\"'"

- name: Set autocd in bashrc
  lineinfile:
    dest: ~/.bashrc
    regexp: 'shopt -s autocd'
    line: 'shopt -s autocd'

- name: Install guake
  package:
    name: guake
    state: present
  become: true

- name: Ensure ~/.pip directory exists
  file:
    path: "~/.pip"
    state: directory
  become: false

- name: Link pip.conf
  file:
    src: "{{ role_path }}/files/pip.conf"
    dest: "~/.pip/pip.conf"
    state: link
  become: false
