---

packages:
  - ansible-lint
  - at
  - bat
  - bmon
  - certbot
  - clipit
  - cloc  # Count lines of code
  - ctags
  - curl
  - entr
  - geany
  - git
  - gnupg
  - gparted
  - htop
  - httpie
  - incron
  - inotify-tools
  - iotop
  - jq
  - lftp
  - lnav
  - mtr
  - multitail
  - ncdu
  - openssl
  - pandoc
  - pdfsam
  - preload
  - pv
  - pwgen
  - pydf
  - ranger
  - renameutils
  - rsync
  - sshpass
  - tig
  - tlp
  - tmux
  - tree
  - xclip
  - xdotool
  - yamllint
  - zathura-pdf-mupdf

packages_arch:
  - cronie
  - openssh
  - perl-rename
  - the_silver_searcher
  - vscode
  - xorg-xkill

packages_debian:
  - anacron
  - apg  # random password generator
  - aptitude
  - build-essential
  - byobu   # For remove-old-kernels
  - git-extras
  - libimage-exiftool-perl
  - openssh-client
  - openssh-server
  - silversearcher-ag
  - texlive-fonts-recommended   # for pandoc to pdf
  - tlp-rdw
  - undistract-me
  - vim-gtk
