- name: Remove sylvia obs wrong repo
  apt_repository:
    repo={{ item }}
    state=absent
    codename="sylvia"
  with_items: "{{ ppas }}"
  become: True

- name: Remove sonya obs wrong repo
  apt_repository:
    repo={{ item }}
    state=absent
    codename="sonya"
  with_items: "{{ ppas }}"
  become: True

- name: Install ppas
  apt_repository:
    repo={{ item }}
    state=present
    codename="beaver"
  with_items: "{{ ppas }}"
  ignore_errors: True
  become: True

- name: Install video packages
  package: 
    name={{ item }} 
    state=present
  with_items: "{{ packages }}"
  become: True
  ignore_errors: True

- name: Install scripts
  file: 
    src="{{ role_path }}/files/{{ item }}"
    dest="/usr/local/bin/{{ item }}"
    state=link
  with_items: "{{ scripts }}"
  become: True

- name: Clone pulverize repo
  git: 
    repo="https://github.com/sciactive/pulverize"
    dest="/var/repos/pulverize"
    
- name: Link pulverize.php into /usr/local/bin
  file:
    src="/var/repos/pulverize/pulverize.php"
    dest="/usr/local/bin/pulverize.php"
    state="link"
  become: True
