- name: Remove sylvia obs wrong repo
  apt_repository:
    repo={{ item }}
    state=absent
    codename="sylvia"
  with_items: "{{ ppas }}"
  become: yes

- name: Remove sonya obs wrong repo
  apt_repository:
    repo={{ item }}
    state=absent
    codename="sonya"
  with_items: "{{ ppas }}"
  become: yes

- name: Install ppas
  apt_repository:
    repo={{ item }}
    state=present
    codename="bionic"
  with_items: "{{ ppas }}"
  ignore_errors: yes
  become: yes

- name: Install video packages
  package: 
    name: "{{ packages }}"
    state: present
  become: yes
  ignore_errors: yes

- name: Install scripts
  file: 
    src="{{ role_path }}/files/{{ item }}"
    dest="/usr/local/bin/{{ item }}"
    state=link
  with_items: "{{ scripts }}"
  become: yes

- name: Remove pulverize repo
  file: 
    path: "/var/repos/pulverize"
    state: absent
  become: yes
    
- name: Remove pulverize link
  file:
    path: "/usr/local/bin/pulverize.php"
    state: absent
  become: yes
