---

- name: Remove sylvia obs wrong repo
  apt_repository:
    repo={{ item }}
    state=absent
    codename="sylvia"
  with_items: "{{ ppas }}"
  become: true
  when: ansible_pkg_mgr=="apt"

- name: Remove sonya obs wrong repo
  apt_repository:
    repo={{ item }}
    state=absent
    codename="sonya"
  with_items: "{{ ppas }}"
  become: true
  when: ansible_pkg_mgr=="apt"

- name: Install ppas
  apt_repository:
    repo={{ item }}
    state=present
    codename="bionic"
  with_items: "{{ ppas }}"
  ignore_errors: true
  become: true
  when: ansible_pkg_mgr=="apt"

- name: Install video packages
  package:
    name: "{{ packages }}"
    state: present
  become: true
  ignore_errors: true

- name: Install scripts
  file:
    src="{{ role_path }}/files/{{ item }}"
    dest="/usr/local/bin/{{ item }}"
    state=link
  with_items: "{{ scripts }}"
  become: true

- name: Remove pulverize repo
  file:
    path: "/var/repos/pulverize"
    state: absent
  become: true

- name: Remove pulverize link
  file:
    path: "/usr/local/bin/pulverize.php"
    state: absent
  become: true
