- name: Install video packages
  package: 
    name={{ item }} 
    state=present
  with_items: "{{ packages }}"
  become: True

- name: Install scripts
  file: 
    src="{{ role_path }}/files/{{ item }}"
    dest="/usr/local/bin/{{ item }}"
    state=link
  with_items: "{{ scripts }}"
  become: True

- name: Ensure repos directory exists
  file:
    path="~/repos"
    state="directory"

- name: Clone pulverize repo
  git: 
    repo="https://github.com/sciactive/pulverize"
    dest="~/repos/pulverize"
    
- name: Link pulverize.php into /usr/local/bin
  file:
    src="~/repos/pulverize/pulverize.php"
    dest="/usr/local/bin/pulverize.php"
    state="link"
