- name: Install video packages
  package: 
    name={{ item }} 
    state=present
  with_items: "{{ packages }}"
  become: True

- name: Install scripts
  file: 
    src="{{ role_path }}/files/{{ item }}"
    dest="/usr/local/bin/{{ item }}"
    state=link
  with_items: "{{ scripts }}"
  become: True

