- name: Ensure ppas are installed
  apt_repository:
    repo: "{{ item }}"
    state: "present"
    codename: "xenial"
    update_cache: True
  with_items: "{{ ppas }}"
  become: True

- name: Install fun packages
  package: 
    name: "{{ item }}" 
    state: present
  with_items: "{{ packages }}"
  become: True
