---

- name: Purge python packages via apt
  package:
    name: "{{ purge_packages }}"
    state: absent
  ignore_errors: true
  become: true
  when: ansible_pkg_mgr=="apt"

- name: Remove python packages via pip in debian family
  pip:
    name: "{{ purge_pip_packages }}"
    state: absent
    executable: pip3
  ignore_errors: true
  become: true
  when: ansible_os_family=="Debian"

- name: Install python packages via apt
  package:
    name: "{{ packages }}"
    state: latest
  ignore_errors: true
  become: true
  when: ansible_pkg_mgr=="apt"

- name: Install python packages via pacman
  package:
    name: "{{ packages_pac }}"
    state: latest
  ignore_errors: true
  become: true
  when: ansible_pkg_mgr=="pacman"

- name: Install python packages via pip in debian family
  pip:
    name: "{{ pip_packages }}"
    state: latest
    executable: pip3
    extra_args: --ignore-installed
  become: true
  ignore_errors: true
  when: ansible_os_family=="Debian"

- name: Ensure ptpython folder exists
  file:
    dest: "{{ ansible_env.HOME }}/.ptpython/"
    state: directory
  become: false

- name: Ptipython config file
  file:
    dest: "{{ ansible_env.HOME }}/.ptpython/config.py"
    state: absent
  become: false
