- name: Ensure repos directory exists
  file:
    path="/var/repos"
    state="directory"
    mode="o+rwx"
  become: True

- name: Update system
  apt: 
    upgrade: safe
    update_cache: True
    cache_valid_time: 0
  become: True

