---

- name: Ensure repos directory exists
  file:
    path="/var/repos"
    state="directory"
    mode="o+rwx"
  become: true

- name: Update debian family system
  apt:
    upgrade: safe
    update_cache: true
    cache_valid_time: 0
  become: true
  when: ansible_os_family=="Debian"

- name: Update arch family system
  pacman:
    upgrade: true
    update_cache: true
  become: true
  when: ansible_os_family=="Archlinux"
