---

purge_packages:
  - python3-matplotlib
  - python3-pandas
  - python3-numpy
  - python3-sympy
  - python3-nose
  - python3-scipy
  - python3-seaborn
  - pylint
  - python3-spyder
  - spyder3

packages:
  - gfortran
  - libcairo2-dev    # for pycairo
  - libcurl4-openssl-dev    # for pycurl
  - libfreetype6-dev    # for matplotlib
  - libgirepository1.0-dev    # for pycairo
  - libicu-dev    # for PyICU
  - libssl-dev    # for pycurl
  - pyenv
  - python-dev    # for pycurl
  - python-pipx
  - python3-dev
  - python3-pip
  - python3-setuptools
  - python3-tk
  - virtualenv

packages_pac:
  - python-poetry
  - pyenv

purge_pip_packages:
  - xonsh
  - wharfee      # docker cli
  - pgcli
  - watchdog
  - ptipython
  - gitsome

pip_packages:
  - yq
  - httpie
  - ipython
  - keyring
  - pytz
  - python-dateutil
  - setuptools
  - youtube-dl
  - patsy
  - pip
  - pandas
  - numpy
  - matplotlib
  - sympy
  - nose
  - pytest
  - pytest-xdist
  - scipy
  - scikit-learn
  - statsmodels
  - seaborn
  - plotly
  - requests
  - scrapy
  - sqlalchemy
  - beautifulsoup4
  - openpyxl
  - psycopg2-binary
  - pylint
  - invoke
  - flake8
  - pyyaml
  - libtmux
  - bpsrender
  - ansible
  - pycairo
