---

purge_packages:
  - python3-matplotlib
  - python3-pandas
  - python3-numpy
  - python3-sympy
  - python3-nose
  - python3-scipy
  - python3-seaborn
  - pylint
  - python3-spyder
  - spyder3

packages:
  - ipython3
  - python3-dev
  - python3-setuptools
  - python3-pip
  - python3-tk
  - gfortran
  - virtualenv
  - libfreetype6-dev # for matplotlib
  - libicu-dev # for PyICU
  - libssl-dev # for pycurl
  - libcurl4-openssl-dev # for pycurl
  - python-dev # for pycurl
  - libcairo2-dev # for pycairo
  - libgirepository1.0-dev # for pycairo

purge_pip_packages:
  - xonsh
  - wharfee #docker cli
  - pgcli
  - watchdog
  - ptipython
  - gitsome
  - tmuxp

pip_packages:
  - httpie
  - ipython
  - keyring
  - pytz
  - python-dateutil
  - setuptools
  - youtube-dl
  - patsy
  - pip
  - pandas
  - numpy
  - matplotlib
  - sympy
  - nose
  - pytest
  - pytest-xdist
  - scipy
  - scikit-learn
  - statsmodels
  - seaborn
  - plotly
  - requests
  - scrapy
  - sqlalchemy
  - beautifulsoup4
  - openpyxl
  - psycopg2-binary
  - pylint
  - invoke
  - flake8
  - pyyaml
  - libtmux
  - bpsrender
  - ansible
  - pycairo
