---
ppas:
  - "ppa:obsproject/obs-studio"

packages:
  - blender
  - ffmpeg
  - obs-studio  # if remove this, remove also his ppa
  - smplayer
  - vlc
  - aegisub

scripts:
  - extractmp3.sh
  - trec2mp4.sh
