
- name: Install dockly
  npm:
    name: dockly
    global: yes
    state: latest
  become: yes

- name: Install util packages
  package: 
    name: "{{ packages }}"
    state: present
  become: yes

- name: Install util packages for arch family
  pacman: 
    name: "{{ packages_arch }}"
    state: present
  become: yes
  when: ansible_pkg_mgr == "pacman"

- name: Install util packages for debian family
  apt: 
    name: "{{ packages_debian }}" 
    state: present
  become: yes
  when: ansible_pkg_mgr == "apt"

- name: Create ansible log file
  copy:
    dest: /var/log/ansible.log
    content: ""
    force: no
    mode: 0666
  become: yes

- name: Set up ansible debug mode
  lineinfile:
    dest: "/etc/ansible/ansible.cfg"
    regexp: '^stdout_callback = debug'
    line: 'stdout_callback = debug'
    insertafter: "^[defaults]"
  become: yes
  ignore_errors: yes

- name: Set up ansible logging
  lineinfile:
    dest: "/etc/ansible/ansible.cfg"
    regexp: '^#?log_path'
    line: 'log_path = /var/log/ansible.log'
  become: yes
  ignore_errors: yes

- name: Activate undistract-me
  lineinfile:
    dest: "~/.bashrc"
    regexp: ".*undistract-me\\.sh.*"
    line: "source /etc/profile.d/undistract-me.sh"
  become: false

- name: Install scripts
  file: 
    src="{{ item }}"
    dest="/usr/local/bin/{{ item | basename }}"
    state=link
  with_fileglob: "{{ role_path }}/files/*.sh"
  become: yes

