---

- name: Install util packages
  package:
    name: "{{ packages }}"
    state: present
  become: true

- name: Install util packages for arch family
  pacman:
    name: "{{ packages_arch }}"
    state: present
  become: true
  when: ansible_pkg_mgr == "pacman"

- name: Install util packages for debian family
  apt:
    name: "{{ packages_debian }}"
    state: present
  become: true
  when: ansible_pkg_mgr == "apt"

- name: Create ansible log file
  copy:
    dest: /var/log/ansible.log
    content: ""
    force: false
    mode: 0666
  become: true

- name: Set up ansible debug mode
  lineinfile:
    dest: "/etc/ansible/ansible.cfg"
    regexp: '^stdout_callback = debug'
    line: 'stdout_callback = debug'
    insertafter: "^[defaults]"
  become: true
  ignore_errors: true

- name: Set up ansible logging
  lineinfile:
    dest: "/etc/ansible/ansible.cfg"
    regexp: '^#?log_path'
    line: 'log_path = /var/log/ansible.log'
  become: true
  ignore_errors: true

- name: Activate undistract-me
  lineinfile:
    dest: "~/.bashrc"
    regexp: ".*undistract-me\\.sh.*"
    line: "source /usr/share/undistract-me/undistract-me.sh"
  become: false

- name: Install scripts
  file:
    src="{{ item }}"
    dest="/usr/local/bin/{{ item | basename }}"
    state=link
  with_fileglob: "{{ role_path }}/files/*.sh"
  become: true
