- name: Install docker packages for debian family
  apt: 
    name: "{{ packages_debian }}"
    state: present
  become: yes
  when: ansible_pkg_mgr == "apt"
  
- name: Install docker packages for arch family
  pacman: 
    name: "{{ packages_arch }}"
    state: present
  become: yes
  when: ansible_pkg_mgr == "pacman"

- name: Install docker packages for all families
  package: 
    name: "{{ packages_common }}"
    state: present
  become: yes

- name: Add current user to docker group
  user: 
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  become: yes
