---

- name: Ensure .vim folder
  file:
      path: ~/.vim
      state: directory
  become: false

- name: Ensure .vim/config folder
  file:
      path: ~/.vim/config
      state: directory
  become: false

- name: Ensure .vim plugin folder
  file:
      path: "~/.vim/pack/bundle/start/"
      state: directory
  become: false

- name: Remove old configuration
  file:
      path: "~/.vim/{{ item }}"
      state: absent
  with_items:
      - "plugged"
      - "README.md"
      - ".gitignore"
      - ".git"
      - "script"
      - "autoload"
  become: false

- name: Copy base config files
  file:
      src: "{{ item }}"
      dest: "~/.vim/{{ item | basename }}"
      state: link
      force: true
  with_fileglob: "{{ role_path }}/files/*"
  become: false

- name: Copy custom config files
  file:
      src: "{{ item }}"
      dest: "~/.vim/config/{{ item | basename }}"
      state: link
      force: true
  with_fileglob: "{{ role_path }}/config/*"

  become: false
- shell: ls -1 ~/.vim/pack/bundle/start/
  register: installed_plugins
  become: false
  changed_when: false

- name: Install prettier
  package:
    name: prettier
    state: latest
  become: true

- name: Remove unused plugins
  file:
      path: "~/.vim/pack/bundle/start/{{ item }}"
      state: absent
  with_items: "{{ installed_plugins.stdout_lines }}"
  when: item not in plugins | map('basename')
  become: false

- name: Install/update plugins
  git:
      repo: 'git@github.com:{{ item  }}.git'
      repo: 'https://github.com/{{ item  }}'
      dest: '~/.vim/pack/bundle/start/{{ item | basename }}'
      update: true
      recursive: false
      depth: 1
  with_items: "{{ plugins }}"
  become: false
  ignore_errors: true

- name: Intall fzf repo
  git:
      repo: 'https://github.com/junegunn/fzf.git'
      dest: '~/.fzf'
      update: true
  register: fzf_result

- name: Install fzf
  command: "~/.fzf/install --all"
  become: false
  when: fzf_result.changed
