
- name: Ensure .vim folder
  file:
      path: ~/.vim
      state: directory
  become: no

- name: Ensure .vim plugin folder
  file:
      path: "~/.vim/pack/bundle/start/"
      state: directory
  become: no

- name: Remove old configuration
  file:
    path: "~/.vim/{{ item }}"
    state: absent
  with_items:
    - "plugged"
    - "README.md"
    - ".gitignore"
    - ".git"
    - "script"
    - "autoload"
  become: no

- name: Copy config files
  file:
      src: "{{ item }}"
      dest: "~/.vim/{{ item | basename }}"
      state: link
      force: yes
  with_fileglob: "{{ role_path }}/files/*"
  become: no

- name: Install/update plugins
  git: 
      repo: 'https://github.com/{{ item  }}'
      dest: '~/.vim/pack/bundle/start/{{ item | basename }}'
      update: yes
  with_items: "{{ plugins }}"
  become: no
  ignore_errors: yes

- name: Intall fzf repo
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: '~/.fzf'
    update: yes
  register: fzf_result

- name: Install fzf 
  command: "~/.fzf/install --all"
  become: no
  when: fzf_result.changed

