- name: Install image packages
  package: 
    name: "{{ packages }}" 
    state: present
  become: yes

- name: Remove pencil folder
  file:
    path: "/var/repos/pencil"
    state: absent
  become: yes
  tags: test


- name: Remove pencil link
  file: 
    path: "/usr/local/bin/pencil"
    state: absent
  become: yes
  tags: test
