- name: Install image packages
  package:
    name: "{{ packages }}"
    state: present
  become: yes
  ignore_errors: yes

- name: Remove pencil folder
  file:
    path: "/var/repos/pencil"
    state: absent
  become: yes

- name: Remove pencil link
  file:
    path: "/usr/local/bin/pencil"
    state: absent
  become: yes
